### ISSUE TITLE
Document is empty error

### ISSUE THREAD

**Issue by cam** [lsmoura/anchorcms-sitemap#1]
Thanks for your work on this @lsmoura. I tried it out and got an empty document error.\

"This page contains the following errors: error on line 1 at column 1: Document is empty"

Any ideas?

**Comment by lsmoura** [comment]
That's interesting. Do you have any other modifications on anchorcms? What URL are you trying to retrieve?

**Comment by cam** [comment]
No other modifications. I'm trying to access it at http://camgould.com/blog/sitemap.xml

**Comment by lsmoura** [comment]
That's... Interesting. Your output content is correct, but it stripped out all xml tags. You're using the 0.9.2 version (downloaded from the site) or the master revision from github? I'll check now if the "master" revision has anything that strips the xml tags and look for a workaround.

I'll download the "master" to another site to make some testings... I've tried to mess around with the 1.0-dev branch, but it seems too experimental at the moment...

Here's my output http://moura.us/sitemap.xml

**Comment by cam** [comment]
I'm just using the one from the Github repo. Your output certainly looks right!
